version: "3.8"

services:

  ghost:
    build:
      context: "./docker/ghost/"
      dockerfile: "dockerfile"
    image: "phoenixaspacio/ghost:latest"
    restart: "always"
    volumes:
      - "./data/ghost/content:/var/lib/ghost/content"
      - "./data/ghost/config.production.json:/var/lib/ghost/config.production.json"
    networks:
      - "phoenix"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    expose:
      - "2368"

  mysql:
    build:
      context: "./docker/mysql/"
      dockerfile: "dockerfile"
    image: phoenixaspacio/mysql:latest
    restart: always
    volumes:
      - "./data/mysql:/var/lib/mysql"
    networks:
      - "phoenix"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      - MYSQL_ROOT_PASSWORD=96CKTjsLJmUNTUzFzx9fpBMrWeLUEvTtzKVmykwJzSUby7fqba
    ports:
      - "0.0.0.0:3306:3306"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    networks:
      - "phoenix"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    volumes:
      - "./data/phpmyadmin/config.inc.php:/etc/phpmyadmin/config.inc.php"
    environment:
      - UPLOAD_LIMIT=1024M
    expose:
      - "80"

  php-fpm:
    build:
      context: "./docker/php-fpm/"
      dockerfile: "dockerfile"
    image: "phoenixaspacio/php-fpm:latest"
    restart: "always"
    volumes:
      - "./data/web:/var/web"
    networks:
      - "phoenix"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    expose:
      - "9000"

  nginx:
    build:
      context: "./docker/nginx/"
      dockerfile: "dockerfile"
    image: "phoenixaspacio/nginx:latest"
    volumes:
      - "./data/nginx/conf:/etc/nginx/conf.d"
      - "./data/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./data/web:/var/web"
    restart: "always"
    networks:
      - "phoenix"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - "0.0.0.0:81:80"
    depends_on:
      - "php-fpm"

  https-portal:
    container_name: "https-portal"
    image: steveltn/https-portal:latest
    restart: always
    environment:
      DOMAINS: |
          aspac.io => https://phoenix.aspac.io,
          www.aspac.io => https://phoenix.aspac.io,
          phoenix.aspac.io -> http://ghost:2368,
          database.aspac.io -> http://phpmyadmin:80,
          cloud.aspac.io -> http://172.17.0.1:11000,
          automate.aspac.io -> http://172.17.0.1:8081,
          accounting.aspac.io -> http://172.17.0.1:8082,
          globe.aspac.io -> http://nginx:80
      STAGE: production
      WEBSOCKET: 'true'
      CLIENT_MAX_BODY_SIZE: 0
    volumes: 
      - "./data/nginx/ssl:/var/lib/https-portal"
      - "./data/https-portal/logs:/var/log/nginx"
      - "./data/web:/var/web"
    networks:
      - "phoenix"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    depends_on:
      - "nginx"
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  ssh:
    build:
      context: "./docker/ssh/"
      dockerfile: "dockerfile"
    image: "phoenixaspacio/ssh:latest"
    volumes:
      - "./data/web:/var/web"
      - "./data/ssh/creds/moduli:/etc/ssh/moduli"
      - "./data/ssh/creds/ssh_host_ecdsa_key:/etc/ssh/ssh_host_ecdsa_key"
      - "./data/ssh/creds/ssh_host_ecdsa_key.pub:/etc/ssh/ssh_host_ecdsa_key.pub"
      - "./data/ssh/creds/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key"
      - "./data/ssh/creds/ssh_host_ed25519_key.pub:/etc/ssh/ssh_host_ed25519_key.pub"
      - "./data/ssh/creds/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key"
      - "./data/ssh/creds/ssh_host_rsa_key.pub:/etc/ssh/ssh_host_rsa_key.pub"
    environment:
      SSH_USER_1: "aspaciop:31102424"
    restart: "always"
    networks:
      - "phoenix"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - "0.0.0.0:2222:22"

networks:

  phoenix:
    driver: "bridge"
